<?php 
/**
 * Default Template
 * 
 * @author Smo
 * @since 07.08.2013
 */
namespace lessonPlaner;
?>
<table class="lessonTable">
	<tr class="tableHeading">
		<td></td>
		<td><?php echo $this->_['monday']; ?></td>
		<td><?php echo $this->_['tuesday']; ?></td>
		<td><?php echo $this->_['wednesday']; ?></td>
		<td><?php echo $this->_['thursday']; ?></td>
		<td><?php echo $this->_['friday']; ?></td>
	</tr>
	<tr class="firstBlock">
		<td><?php echo $this->_['block1']; ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['mo1']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['di1']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['mi1']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['do1']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['fr1']); ?></td>
	</tr>
	<tr class="secondBlock">
		<td><?php echo $this->_['block2']; ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['mo2']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['di2']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['mi2']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['do2']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['fr2']); ?></td>
	</tr>
	<tr class="thirdBlock">
		<td><?php echo $this->_['block3']; ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['mo3']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['di3']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['mi3']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['do3']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['fr3']); ?></td>
	</tr>
	<tr class="fouthBlock">
		<td><?php echo $this->_['block4']; ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['mo4']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['di4']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['mi4']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['do4']); ?></td>
		<td><?php echo Model::getBlockEntryById($this->_['planEntries']['0']['fr4']); ?></td>
	</tr>
</table>
<span class="linkSet">
	<a href="?view=new"><button class="newPlan">Neu</button></a>
	<a href="?view=edit"><button class="editPlan">Bearbeiten</button></a>
	<a href="?view=print"><button class="printPlan">Drucken</button></a>
	<a href="?view=send"><button class="sendPlan">Per E-Mail senden</button></a>
	<a href="?view=share"><button class="sharePlane">Auf Facebook teilen</button></a>
</span>
