<?php 
/**
 * Default Template
 * 
 * @author Smo
 * @since 07.08.2013
 */
namespace lessonPlaner;
?>
<span class="default">
	<table class="lessonTable">
		<tr class="tableHeading">
			<td>
				Montag
			</td>
			<td>
				Dienstag
			</td>
			<td>
				Mittwoch
			</td>
			<td>
				Donnerstag
			</td>
			<td>
				Freitag
			</td>
		</tr>
		<tr class="firstBlock">
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
		</tr>
		<tr class="secondBlock">
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
		</tr>
		<tr class="thirdBlock">
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
		</tr>
		<tr class="fouthBlock">
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
			<td>
				&nbsp;
			</td>
		</tr>
	</table>
</span>