<?php 
/**
 * Default Template
 * 
 * @author Smo
 * @since 07.08.2013
 */
namespace lessonPlaner;


dump($this->_['planEntries']);
?>
<span class="default">
	<table class="lessonTable">
		<tr class="tableHeading">
			<td></td>
			<td><?php echo $this->_['monday']; ?></td>
			<td><?php echo $this->_['tuesday']; ?></td>
			<td><?php echo $this->_['wednesday']; ?></td>
			<td><?php echo $this->_['thursday']; ?></td>
			<td><?php echo $this->_['friday']; ?></td>
		</tr>
		<tr class="firstBlock">
			<td><?php echo $this->_['block1']; ?></td>
			<td><?php dump(Model::getPlanEntryByTag($this->_['planEntries']['0']['mo1'])); ?></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr class="secondBlock">
			<td><?php echo $this->_['block2']; ?></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr class="thirdBlock">
			<td><?php echo $this->_['block3']; ?></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr class="fouthBlock">
			<td><?php echo $this->_['block4']; ?></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</table>
	<a href="?view=new"><button class="newPlan">Neu</button></a>
	<a href="?view=edit"><button class="editPlan">Bearbeiten</button></a>
	<a href="?view=print"><button class="printPlan">Drucken</button></a>
	<a href="?view=send"><button class="sendPlan">Per E-Mail senden</button></a>
	<a href="?view=share"><button class="sharePlane">Auf Facebook teilen</button></a>
</span>