<?php 
/**
 * Aeußeres Template
 * 
 * @author Smo
 * @since 07.08.2013
 */
namespace lessonPlaner;
?>
<!DOCTYPE html PUBLIC “-//W3C//DTD XHTML 1.0 Strict//EN” ”http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd”>
<html>
	<head>
		<title><?php echo $this->_['title']; ?></title>
		<link rel="stylesheet" href="css/main.css" />
	</head>
	<body>
		<h1 class="heading"><?php echo $this->_['heading']; ?></h1>
		<?php echo $this->_['content']; ?>
		<hr />
		<span class="footer"><?php echo $this->_['footer']; ?></span>
	</body>
</html>