<?php 
/**
 * Aeußeres Template
 * 
 * @author Smo
 * @since 07.08.2013
 */
namespace lessonPlaner;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<title><?php echo $this->_['title']; ?></title>
		<link rel="stylesheet" href="css/main.css" />
		<link rel="stylesheet" href="css/jquery_overlay.css" />
		<script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
		<script type="text/javascript" src="js/jquery_overlay.js"></script>
		<script type="text/javascript">
			$.fn.overlay();
		</script>
	</head>
	<body>
		<h1 class="heading"><?php echo $this->_['heading']; ?></h1>
		<hr />
		<?php echo $this->_['content']; ?>
		<hr />
		<span class="footer"><?php echo $this->_['footer']; ?></span>
	</body>
</html>