<?php 
/**
 * Äußeres Template
 * 
 * @author Smo
 * @since 07.08.2013
 */
namespace lessonPlaner;
?>

<html>
	<head>
		<title><?php echo $this->_['title']; ?></title>
		<link rel="stylesheet" href="css/main.css" />
	</head>
	<body>
		<h1 class="heading"><?php echo $this->_['heading']; ?></h1>
		<?php echo $this->_['content']; ?>
		<hr />
		<span class="footer"><?php echo $this->_['footer']; ?></span>
	</body>
</html>