<?php 
/**
 * new.phtml - Template fuer Neuerstellung
 * 
 * @author Smo
 * @since 09.08.2013
 */
namespace lessonPlaner;

if (isset($_POST['inputFach']) && isset($_POST['inputRaum']) && isset($_POST['inputLehrer']))
{
	// TODO: POST Daten prüfen!
	Model::saveBlockEntry($_POST['inputFach'], $_POST['inputRaum'], $_POST['inputLehrer']);
	
	unset($_POST);
	echo $this->_['blockCreated'];
}
if (isset($_POST['blockSelection']) && isset($_POST['timeSelection']))
{
	$block = Model::getBlockEntryByTag($_POST['blockSelection']);
		
	Model::savePlanEntry($block, $_POST['timeSelection']);
	unset($_POST);
	
	// TODO: enum für Wochentag<->Block
	echo "Fach: {$block['fach']}<br />Raum: {$block['raum']}<br />Lehrer: {$block['lehrer']}<br />";
}
if (isset($_POST['clear']))
{
	if(Model::clearPlan())
	{
		echo $this->_['planCleared'];
	}
}
?>
<h2><?php echo $this->_['headingBlock']; ?></h2>
<form class="form" action="" method="post">
	<label for="inputFach"><?php echo $this->_['inputFachLabel']; ?></label>
	<input class="inputFach" type="text" name="inputFach" value="" />
	<label for="inputRaum"><?php echo $this->_['inputRaumLabel']; ?></label>
	<input class="inputRaum" type="text" name="inputRaum" value="" />
	<label for="inputLehrer"><?php echo $this->_['inputLehrerLabel']; ?></label>
	<input class="inputLehrer" type="text" name="inputLehrer" value="" />
	
	<input class="submit" type="submit" value="Speichern" />
</form>
<hr />
<?php 
$entries = Model::getBlockEntries();
$this->assign('blockEntries', $entries);
?>
<h2><?php echo $this->_['headingBlock2Plan']; ?></h2>
<p><?php echo $this->_['chooseABlock']; ?></p>
<form class="form" action="" method="post">
	<select class="select" name="blockSelection" size="<?php echo count($this->_['blockEntries']); ?>">
		<?php 
			foreach ($this->_['blockEntries'] as $entry)
			{
				echo "<option>" . $entry['fach'] . "</option>";
			}
		?>
	</select>
	<select class="select" name="timeSelection" size="<?php echo count($this->_['blockEntries']); ?>">
		<optgroup label="Montag">
			<option value="mo1"><?php echo $this->_['block1']; ?></option>
			<option value="mo2"><?php echo $this->_['block2']; ?></option>
			<option value="mo3"><?php echo $this->_['block3']; ?></option>
			<option value="mo4"><?php echo $this->_['block4']; ?></option>
		</optgroup>
		<optgroup label="Dienstag">
			<option value="di1"><?php echo $this->_['block1']; ?></option>
			<option value="di2"><?php echo $this->_['block2']; ?></option>
			<option value="di3"><?php echo $this->_['block3']; ?></option>
			<option value="di4"><?php echo $this->_['block4']; ?></option>
		</optgroup>
		<optgroup label="Mittwoch">
			<option value="mi1"><?php echo $this->_['block1']; ?></option>
			<option value="mi2"><?php echo $this->_['block2']; ?></option>
			<option value="mi3"><?php echo $this->_['block3']; ?></option>
			<option value="mi4"><?php echo $this->_['block4']; ?></option>
		</optgroup>
		<optgroup label="Donnerstag">
			<option value="do1"><?php echo $this->_['block1']; ?></option>
			<option value="do2"><?php echo $this->_['block2']; ?></option>
			<option value="do3"><?php echo $this->_['block3']; ?></option>
			<option value="do4"><?php echo $this->_['block4']; ?></option>
		</optgroup>
		<optgroup label="Freitag">
			<option value="fr1"><?php echo $this->_['block1']; ?></option>
			<option value="fr2"><?php echo $this->_['block2']; ?></option>
			<option value="fr3"><?php echo $this->_['block3']; ?></option>
			<option value="fr4"><?php echo $this->_['block4']; ?></option>
		</optgroup>
	</select>
	<input class="submit" type="submit" value="Speichern" />
</form>
<!-- Clear planer -->
<hr>
<h2><?php echo $this->_['headingClear']; ?></h2>
<form class="form" action="" method="post">
	<input class="submit" type="submit" value="Ja!" name="clear" />
</form>
<hr>
<a href="?view=default"><button class="back">Zur&uuml;ck</button></a>
























